version: '3'
services:
  redis:
    container_name: redis
    image: redis:7.0
    command: /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 32774:6379
    sysctls:
      - net.core.somaxconn=324000
      - net.ipv4.tcp_max_syn_backlog=3240000
    restart: always