name: Linting

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Run tests with pytest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install ffmpeg
        run: sudo apt update && sudo apt-get install ffmpeg -y
      - name: Build the docker-compose stack
        run: docker compose -f docker/docker-compose.yml up -d
      - name: Check running containers
        run: docker ps

      - name: Set up WireGuard Connection
        uses: niklaskeerl/easy-wireguard-action@50341d5f4b8245ff3a90e278aca67b2d283c78d0
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}

      - run: pip install -r requirements.txt
      - name: Run Tests
        timeout-minutes: 5
        run: pytest
