name: Docker image build for worker
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  worker:
    uses: ./.github/workflows/docker-build.yml
    with:
      name: "thumbnail-cache-worker"
      username: "ajayyy"
      folder: "."
      file: "Dockerfile-worker"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}